use_sim_time: true
gui: true
graph: stanford
init_bots: 9
init_locations: ''
done: false
sim_length: 3000
random_string: 'test2'
algo_name: 'iot_communication_network'
no_of_deads: 0
run_id: 0
iot_device_range: 150
